import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import { providers, utils } from "ethers";
import { WebBundlr } from "@bundlr-network/client";
import { useState, useEffect, useRef, useContext } from "react";
import { MainContext } from "../context";
import BigNumber from "bignumber.js";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [file, setFile] = useState();
  const [image, setImage] = useState();
  const [URI, setURI] = useState();
  const [amount, setAmount] = useState();

  const { initialize, bundlrInstance, bundlrRef, balance, fetchBalance } =
    useContext(MainContext);

  async function fundWallet() {
    if (!amount) return;
    const parsedAmount = new BigNumber(amount).multipliedBy(
      bundlrInstance.currencyConfig.base[1]
    );
    console.log(parsedAmount, amount);
    if (parsedAmount > 1) {
      const response = await bundlrInstance.fund(parsedAmount);
      console.log("Wallet Funded : ", response);
      fetchBalance();
    }
  }

  async function uploadFile() {
    console.log(file);
    let tx = await bundlrInstance.uploader.chunkedUploader.uploadData(file, [
      { name: "Content-type", value: "image/png" },
    ]);
    console.log(tx);
    setURI(`https://arweave.net/${tx.data.id}`);
  }

  async function uploadFile2() {
    console.log(file);
    let tx = await bundlrInstance.upload(file);
    console.log(tx);
    setURI(`https://arweave.net/${tx.data.id}`);
  }

  function onFileChange(e) {
    const file = e.target.files[0];
    if (file) {
      const image = URL.createObjectURL(file);
      setImage(image);
      let reader = new FileReader();
      reader.onload = function () {
        if (reader.result) {
          setFile(Buffer.from(reader.result));
        }
      };
    }
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>Get started by intializing the bundlr</p>
          <div>
            <a
              href="https://twitter.com/0xdhruva"
              target="_blank"
              rel="noopener noreferrer"
            >
              By @0xdhruva
            </a>
          </div>
        </div>

        <div className={styles.center}>
          <div>
            {balance && <h3 className={styles.button}>Balance : {balance}</h3>}
          </div>
          {!bundlrInstance ? (
            <button className={styles.button} onClick={initialize}>
              Initialize bundlr
            </button>
          ) : (
            <>
              <div>
                <input
                  className={styles.input}
                  onChange={(e) => {
                    setAmount(e.target.value);
                  }}
                  placeholder="Amout to fund wallet"
                ></input>
              </div>
              <h1 className={styles.button}>Bundlr Intialized</h1>
              <button className={styles.button} onClick={fundWallet}>
                Fund Wallet
              </button>
              <div>
                <input
                  className={styles.inputFile}
                  onChange={(e) => {
                    onFileChange(e);
                  }}
                  type="file"
                  placeholder="Amout to fund wallet"
                ></input>
              </div>
              <button className={styles.button} onClick={uploadFile}>
                Upload File
              </button>

              {URI && (
                <a href={URI} target="_blank" rel="noopener noreferrer">
                  {URI}
                </a>
              )}
              {image && <img src={image} style={{ width: "500px" }} />}
            </>
          )}
        </div>
      </main>
    </>
  );
}
